# -*- coding: utf-8 -*-
"""SET50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8nDVaaD4un7aYvYvXbYR_Ib0lYKF5GX
"""

!pip install selenium webdriver-manager pandas

import json, time, sys
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ─ SET50 H1/2026 ─
SET50 = [
    "ADVANC","AOT","AWC","BANPU","BBL","BDMS","BEM","BH","BJC","BTS",
    "CBG","CCET","CENTEL","COM7","CPALL","CPF","CPN","CRC","DELTA","EGCO",
    "GPSC","GULF","HMPRO","IVL","KBANK","KKP","KTB","KTC","LH","MINT",
    "MTC","OR","OSP","PTT","PTTEP","PTTGC","RATCH","SAWAD","SCB","SCC",
    "SCGP","TCAP","TIDLOR","TISCO","TLI","TOP","TRUE","TTB","TU","WHA",
]

URL_TEMPLATE = "https://www.set.or.th/en/market/product/stock/quote/{symbol}/major-shareholders"

def setup_driver():
    try:
        import shutil
        if not shutil.which("google-chrome"):
            print("Installing Google Chrome...")
            !apt-get update > /dev/null
            !apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libgbm1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libxss1 libxtst6 xdg-utils > /dev/null
            !wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            !dpkg -i google-chrome-stable_current_amd64.deb > /dev/null 2>&1 || apt-get install -fy > /dev/null 2>&1
            !rm google-chrome-stable_current_amd64.deb
    except Exception as e: print(f"Setup Error: {e}")

    opts = Options()
    opts.add_argument("--headless")
    opts.add_argument("--no-sandbox")
    opts.add_argument("--disable-dev-shm-usage")
    opts.add_argument("--window-size=1920,1080")
    opts.add_argument("--disable-blink-features=AutomationControlled")
    opts.add_experimental_option("excludeSwitches", ["enable-automation"])
    opts.add_experimental_option("useAutomationExtension", False)
    opts.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

    opts.binary_location = '/usr/bin/google-chrome'
    service = Service(ChromeDriverManager().install())
    return webdriver.Chrome(service=service, options=opts)

def scrape_symbol(driver, symbol, max_shareholders=5):
    url = URL_TEMPLATE.format(symbol=symbol)
    driver.get(url)
    shareholders = []
    try:
        WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "table tbody tr"))
        )
        rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
        for row in rows:
            if len(shareholders) >= max_shareholders: break
            cols = row.find_elements(By.TAG_NAME, "td")
            if len(cols) >= 3:
                name = cols[1].text.strip()
                pct_str = cols[-1].text.strip().replace(",", "")
                if not name or any(x in name for x in ["Total", "%", "Rank", "As of"]):
                    continue
                try:
                    pct = float(pct_str)
                    shareholders.append({"name": name, "pct": pct})
                except:
                    continue
    except Exception as e:
        print(f" ☢ Error {symbol}: {e}")
    return shareholders

def main():
    driver = setup_driver()
    driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
      "source": """
        Object.defineProperty(navigator, 'webdriver', {
          get: () => undefined
        })
      """
    })

    all_data = {}
    total = len(SET50)

    for i, symbol in enumerate(SET50, 1):
        print(f"[{i:2d}/{total}] Scraping {symbol}... ", end="", flush=True)
        res = scrape_symbol(driver, symbol)
        all_data[symbol] = res
        print(f"✓ Found {len(res)}")
        time.sleep(1)

    driver.quit()
    with open("shareholders.json", "w", encoding="utf-8") as f:
        json.dump(all_data, f, ensure_ascii=False, indent=2)
    print(f"\nDone! Data for {len(all_data)} stocks saved to shareholders.json")

if __name__ == "__main__":
    main()